### ISSUE TITLE
Exception every second

### ISSUE THREAD

**Issue by mzieg** [SHUR1K-N/SkipNinja-Amazon-Prime-Video-Intro-Skipper#1]
https://github.com/SHUR1K-N/SkipNinja-Amazon-Prime-Video-Intro-Skipper/blob/a2c35c8db17d21953d8d281cee5e59de02bb2772/Autoskip.pyw#L12

Just skimming your code, looks like you never set skippedFlag to False, so essentially you’re raising and catching an undefined variable exception once per second instead of simply returning False.

**Comment by SHUR1K-N** [comment]
Good catch! I implemented this within the Hotkey.pyw script, but it seems I had forgotten to do the same with Autoskip.pyw. This will be fixed shortly.
